name: Generate Pac-Man Style Animation

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate snake (Pac-Man style)
        uses: Platane/snk@v3
        with:
          github_user_name: Ithaisa1
          outputs: |
            dist/pacman.svg?palette=github-dark&color_snake=%23FFD700&color_dots=%23FFFFFF

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
